### ISSUE TITLE
Feedback on swagger for 2.0 spec implementation

### ISSUE THREAD

**Issue by fehguy** [springdox/swagger-springmvc#387]
Howdy, as we're coming to a close on the swagger 2.0 specification, the swagger-core module has been completely rewritten and should be much easier to work with in Java.  Can you provide any feedback to the new modules here:

https://github.com/wordnik/swagger-core/tree/develop_2.0/modules/swagger-core

https://github.com/wordnik/swagger-core/tree/develop_2.0/modules/swagger-jaxrs

There is a mostly working sample here:

https://github.com/wordnik/swagger-core/tree/develop_2.0/samples/java-jaxrs

which still has a few bugs but is mostly working.

**Comment by dilipkrish** [comment]
Have a fairly close to release version here based on swagger-core models [here](https://github.com/springdox/swagger-springmvc/tree/refactor/538/spike-to-seperate-models-and-dtos). Closing this issue.
