### ISSUE TITLE
Date/Date Time formats

### ISSUE THREAD

**Issue by adrianbk** [springdox/swagger-springmvc#487]
Investigate and implement how to use the JSON spec types date and date-time types for java.util.date and Joda dates. Should apply to models and parameters. Right now it seems like we add direct model substitutes to Strings to allow dates. 

Should apply to :

- Model generation
- All non-body swagger parameter types
- Expanded parameter types (@ModelAttribute)

**Comment by dilipkrish** [comment]
Fixed via [refactoring](https://github.com/springdox/swagger-springmvc/tree/refactor/538/spike-to-seperate-models-and-dtos)
