### ISSUE TITLE
Implement new swagger ResponseObject

### ISSUE THREAD

**Issue by adrianbk** [springdox/swagger-springmvc#488]
https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#responseObject

- Remove old and troublesome defaultResponseCodes
- There's a bunch of related issue which should be considered here: https://github.com/martypitt/swagger-springmvc/issues/438

**Comment by dilipkrish** [comment]
Fixed via [refactoring](https://github.com/springdox/swagger-springmvc/tree/refactor/538/spike-to-seperate-models-and-dtos)
