### ISSUE TITLE
Implement collectionFormats on parameters

### ISSUE THREAD

**Issue by adrianbk** [springdox/swagger-springmvc#490]
Relates to allowableValues on com.wordnik.swagger.annotations.ApiParam.
See [here](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#parameterObject) for supported collection types

**Comment by dilipkrish** [comment]
Fixed via [refactoring](https://github.com/springdox/swagger-springmvc/tree/refactor/538/spike-to-seperate-models-and-dtos)
