### ISSUE TITLE
Provide a hook to configure the grouping of operations

### ISSUE THREAD

**Issue by adrianbk** [springdox/swagger-springmvc#492]
The grouping of swagger operations on swagger-ui is now controlled by tags on the [operation](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#operation-object-). Given that the entire swagger JSON is now a single http endpoint it a appears far simpler to determine a resource grouping and we could potentially eliminate the need for and complexity of ClassOrApiAnnotationResourceGrouping. We should also provide an easy way to extend or hook into how tags are assigned to operations.

**Comment by dilipkrish** [comment]
Currently uses the existing resource grouping to generate tags based on groups generated via ```ClassOrApiAnnotationResourceGrouping```.

Fixed via [refactoring](https://github.com/springdox/swagger-springmvc/tree/refactor/538/spike-to-seperate-models-and-dtos)
