### ISSUE TITLE
Ref vs non-ref models 

### ISSUE THREAD

**Issue by adrianbk** [springdox/swagger-springmvc#493]
Seems like the safest way to attach models to operations is to embed them directly within the operations that use them - it avoids model name clashes. Only reason I can see for globally defining the models is to a achieve a smaller footprint on the generated swagger JSON.  Should we support both?

Right now swagger-ui expects all models to be available as global `'definitions`  See [this issue](https://github.com/swagger-api/swagger-ui/issues/705) Should we support both. 
Example: http://petstore.swagger.wordnik.com/v2/swagger.json

**Comment by dilipkrish** [comment]
This has been addressed currently by making all the models very shallow and have references to other models. There is no support for inlining models in this [refactoring](https://github.com/springdox/swagger-springmvc/tree/refactor/538/spike-to-seperate-models-and-dtos)
