### ISSUE TITLE
Spike to provide a swagger agnostic service model and have that render the swagger spec projection

### ISSUE THREAD

**Issue by dilipkrish** [springdox/swagger-springmvc#538]
Furthering [this discussion](https://github.com/martypitt/swagger-springmvc/commit/19bfc5f2b02df1eeb9e27e9afa4bbc267c7bdd79#commitcomment-9005811) this is a feature to spike the approach.

- [x] Move the DTOs to a separate module
- [x] Remove jackson annotations on the new models
- [x] Write a Mapping Layer that can transform the service model to a swagger specification representation
  - [x] try using the idea of JacksonModule for different representations
  - [x] try out MapStruct and/or ModelMapper 
- [x] Make sure all the tests pass for swagger spec
- [x] Make the logical model truly agnostic of dto 
  - **EDIT:** Currently it is seperated, however keeping the same names and structure. Its probably better to let it evolve on a per-need basis. Removed "swagger"yness from the service models as I found them.
  - **EDIT:** Separated the spring stuff from the swagger stuff. Now it should be easy to separate the code into modules 
- [x] Create a plugin architecture ```spring-plugin``` for the different representations of the logical model. i.e. swagger v1.2, swagger v2, etc.
  - [x] Make the command handlers auto wired so that they can be injected. 
    - **EDIT:** these are ready to go, just need to make the readers and scanners with default constructors, beans.
    - **EDIT:** need to figure out the packages 
  - [x] Refactor ApiModelReader to be more readable, it is very dense
  - [x] Improve the model coverage
  - [x] Fix ignored tests
  - [x] Add test to verify that swagger plugins augment models and properties correctly. 
      - [x] Move the specs to the right packages as well
  - [x] Remove the SwaggerGlobalSettings class since typeResolver/alternateTypeProvider are injected as auto wired properties
  - [x] Pass all the context that commands need as strongly typed accessors
  - [x] Separate the idea of commands into discrete "documentation pack"s. Currently its inlined as a list of commands that is specific to swagger 1.2. Also its not separated in terms of pure spring-mvc and pure swagger.
  - [x] Provide a way to inject "documentation packs". The base "pack" is springmvc. Allow layering of "spring rest data", "swagger" etc. on top of the base pack.
- [x] Artifact release
  - [x] What version should this be released as? **2.0.0**
  - [x] Naming of the modules? package names? what should they be?

**Comment by dilipkrish** [comment]
@adrianbk pushed a WIP to allow plugins ... still **VERY** rough. Its contract compatible and tests pass, so I thought I'd push it out for  feedback... code-review... 

Also updated the todos.

**Comment by adrianbk** [comment]
@dilipkrish looks good with one or two comments. Pumped to start getting different documentation formats and swagger versions going :+1:

**Comment by dilipkrish** [comment]
yup me too :) Still working out a few more changes :point_up: that are in flight, plus your comments... should have something to try and experiment with other formats this weekend.

**Comment by dilipkrish** [comment]
@adrianbk Still have a few lose ends to tie but, I've managed to separate the spring mvc stuff from the swagger stuff into distinct packages. I've also tried to remove a few "swaggerisms" to make it agnostic of the end representation. 

Its all still in the same two modules, but there is a separation on whats core and the swagger documentation pack. So it'll be easy when it comes time to separate into different modules.

I'd be curious what you experience might be trying to layer the swagger 2.0 implementation that you started on top of what we have, and any other feedback you might have. 

We probably need to go over all the public api and tighten stuff up. May be do a code-walk through next week? Could figure out all things naming as well.. .packages/modules and also versioning.

**Comment by dilipkrish** [comment]
Based on [this comment](https://github.com/martypitt/swagger-springmvc/issues/550#issuecomment-68945141)

proposing to move the modules to look like this

mangdocs-core - core models, contexts and builders used by spi :point_down: 
mangodocs-spi - Service provider interface
mangodocs-schema - Schema parser implementation thats agnostic of any documentation format
mangodocs-spring-web - Service model parser thats specific to spring mvc
mangocs-swagger - Schema/Service parser extensions specific to swagger

created a root package com.mangofactory.documentation....
- [x] Move classes to the respective packages
- [ ] Move the tests to the respective packages

**Comment by dilipkrish** [comment]
Moving task from the main issue so that its easy to track...
- [ ] Refactor the ModelXXXXSupport plugins to reduce repetition and also functionality duplication
- [ ] Use traits instead of @Mixin
- [ ] Remove the component scanning once the package structure is finalized
- [ ] Fix ordering of response codes and also anything else that expects order. We lost that due to the mapping layer. 

Yet to do
- [ ] Currently all plugins return true when asked if they support documentation a given documentation type. 
- [ ] Improve coverage. Currently not all modules have pre-refactoring coverage
- [ ] Find a way to isolate ObjectMapper. Probably use the same technique used by spring-hateoas to isolate it.
- [ ] Currently the ```DocumentationPluginsBootstrapper``` also provides the defaults. Extract that to a a class that provides default plugin values 
- [ ] Document the heck out of the spi module

**Comment by dilipkrish** [comment]
Closing this issue as its technically done, with the exception of 
- Documentation of SPI module
- moving from using mixins to traits (which can be done incrementally
- Test refactoring (cleanup of ignored tests; either delete or move to a more appropriate module
