### ISSUE TITLE
make all the property required by default

### ISSUE THREAD

**Issue by a-moncer** [springdox/swagger-springmvc#553]
Hi

i'm using swagger-springmvc and i need to make all the property required how can i do it without adding @ApiModelProperty(required = true) annotation to each property.
 it's more simple for me if i can make all the porerties required by default and the add @ApiModelProperty(required = false) to the few optional ones.

or adding some annotation to a model to say that all his properties are required. 

Thanks

**Comment by dilipkrish** [comment]
Extensibility available via plugins.
 Fixed via [refactoring](https://github.com/springdox/swagger-springmvc/tree/refactor/538/spike-to-seperate-models-and-dtos)

**Comment by natetyler** [comment]
Your link is broken, I'm assuming you deleted the branch. I would also like this functionality, can you provide more information on how to do this via plugins?
