### ISSUE TITLE
com.wordnik.swagger.model.ApiInfo has been deprecated 

### ISSUE THREAD

**Issue by mrwanny** [springdox/swagger-springmvc#605]
com.wordnik.swagger.model.ApiInfo has been deprecated and may need to be replaced by 
com.wordnik.swagger.models.Info

**Comment by dilipkrish** [comment]
@mrwanny This should be fixed in an upcoming release that supports swagger 2.0

**Comment by mrwanny** [comment]
Yes, I actually submit a merge request to the swagger 2.0 branch... 
(some spec are failing in the project... but they are not related with the changes I made)
Please let me know if you have any feedback.

**Comment by dilipkrish** [comment]
Fixed via [refactoring](https://github.com/springdox/swagger-springmvc/tree/refactor/538/spike-to-seperate-models-and-dtos)
